from tkinter import *
login1 =Tk()
login1.title("Login page")
login1.geometry("400x250")
login1.configure(bg="grey")
title1=Label(login1,text="Login page",font=("Arial Bold",30),fg="Grey",bg="Black" ).grid(row=0,column=20)
name = Label(login1,text="Name:",fg="Grey",bg="Black").grid(row=1,column=10,sticky=E)
e1=Entry(login1).grid(row=1,column=20)
email = Label(login1,text="Email:",fg="Grey",bg="Black").grid(row=2,column=10,sticky=E)
e2=Entry(login1).grid(row=2,column=20)
password=Label(login1,text="Password(at least 8 character):",fg="Grey",bg="Black").grid(row=3,column=10,sticky=E)
e3=Entry(login1).grid(row=3,column=20)
phonenumber=Label(login1,text="Mobile Number:",fg="Grey",bg="Black").grid(row=4,column=10,sticky=E)
e4=Entry(login1).grid(row=4,column=20)
submit=Button(login1,text="Submit").grid(row=7,column=20)
login1.mainloop()